apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: eb4asdum4-go 
  janus-idp.io/tekton: eb4asdum4-go
  backstage.io/kubernetes-id: eb4asdum4-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: eb4asdum4-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  